spring:
  application:
    name: libreria-api
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/libreria}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

logging:
  level:
    "[org.springframework.security]": DEBUG

jwt:
  secret:
    key: ${SECRET_KEY}
  expiration: 900000
  refresh:
    duration: 604800000
